"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(nuc)%anrfcfywhi(+w^bw3gpqm9g67_!$x+wgela*gobni+ys'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['http://127.0.0.1/', 'localhost', '*',"archivewebsite.pythonanywhere.com"]

STATIC_ROOT = BASE_DIR / 'staticfiles'
# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    "django_filters",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ar'

# Ensure internationalization is enabled
USE_I18N = True

TIME_ZONE = 'Asia/Baghdad' # UTC+3
USE_TZ = True

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

UNFOLD = {
    "SITE_TITLE": "نظام الأرشفة الإلكترونية",
    "SITE_HEADER": "الأرشيف الإلكتروني",
    "SITE_SUBHEADER": "إدارة الكتب والوثائق والمرفقات",
    "SITE_URL": "/admin/",
    "SITE_FAVICON": "images/logo.svg",
    "SITE_ICON": lambda request: static("images/logo.svg"),
    
    
    "SITE_DROPDOWN": [
        {
            "icon": "database",
            "title": _("لوحة النظام"),
            "link": "/admin/",
        },
        {
            "icon": "inbox",
            "title": _("الكتب المؤرشفة"),
            "link": "/admin/api/archivedocument/",
        },
        {
            "icon": "folder",
            "title": _("الأقسام"),
            "link": "/admin/api/department/",
        },
        {
            "icon": "tag",
            "title": _("الكلمات المفتاحية"),
            "link": "/admin/api/keyword/",
        },
    ],

    "DASHBOARD_CALLBACK": "api.admin_dashboard.dashboard_callback",
}

