# Generated by Django 6.0.5 on 2026-05-05 23:54

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القسم')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز القسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='api_departm_code_dcd7e2_idx'), models.Index(fields=['name'], name='api_departm_name_cbbdb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجهة الخارجية')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='رمز الجهة الخارجية')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'جهة خارجية',
                'verbose_name_plural': 'الجهات الخارجية',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_externa_name_10a5e9_idx'), models.Index(fields=['code'], name='api_externa_code_0b6c09_idx')],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الكلمة المفتاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كلمة مفتاحية',
                'verbose_name_plural': 'الكلمات المفتاحية',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_keyword_name_36ab15_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_kind', models.CharField(choices=[('internal_outgoing', 'صادر داخلي'), ('internal_incoming', 'وارد داخلي'), ('external_outgoing', 'صادر خارجي'), ('external_incoming', 'وارد خارجي')], db_index=True, max_length=32, verbose_name='نوع الكتاب')),
                ('document_number', models.CharField(db_index=True, max_length=100, verbose_name='رقم الكتاب')),
                ('document_date', models.DateField(db_index=True, verbose_name='تاريخ الكتاب')),
                ('subject', models.CharField(db_index=True, max_length=255, verbose_name='موضوع الكتاب')),
                ('content', models.TextField(blank=True, verbose_name='محتوى الكتاب')),
                ('file_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='رقم الفايل')),
                ('storage_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='رقم الخزن')),
                ('archive_box_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الصندوق')),
                ('archive_folder_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المجلد')),
                ('archive_location_note', models.CharField(blank=True, max_length=255, verbose_name='موقع الحفظ')),
                ('pages_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('copies_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد النسخ')),
                ('confidentiality', models.CharField(choices=[('normal', 'عادي'), ('internal', 'داخلي'), ('confidential', 'سري'), ('top_secret', 'سري جداً')], db_index=True, default='normal', max_length=20, verbose_name='درجة السرية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('registered', 'مُسجل'), ('archived', 'مؤرشف'), ('closed', 'مغلق')], db_index=True, default='registered', max_length=20, verbose_name='الحالة')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('main_file', models.FileField(blank=True, null=True, upload_to=api.models.archive_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'tif', 'tiff', 'bmp', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt', 'rtf', 'odt', 'ods']), api.models.validate_file_size], verbose_name='الملف الرئيسي')),
                ('file_original_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('file_checksum', models.CharField(blank=True, max_length=128, verbose_name='بصمة الملف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_archive_documents', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_archive_documents', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة')),
                ('destination_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to='api.department', verbose_name='القسم الوارد إليه')),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_documents', to='api.department', verbose_name='القسم الصادر منه')),
                ('destination_external_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to='api.externalparty', verbose_name='الجهة الخارجية الوارد إليها')),
                ('source_external_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_documents', to='api.externalparty', verbose_name='الجهة الخارجية الصادر منها')),
                ('keywords', models.ManyToManyField(blank=True, related_name='documents', to='api.keyword', verbose_name='الكلمات المفتاحية')),
            ],
            options={
                'verbose_name': 'كتاب مؤرشف',
                'verbose_name_plural': 'الكتب المؤرشفة',
                'ordering': ['-document_date', '-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveDocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان المرفق')),
                ('file', models.FileField(upload_to=api.models.attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'tif', 'tiff', 'bmp', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt', 'rtf', 'odt', 'ods']), api.models.validate_file_size], verbose_name='الملف')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.archivedocument', verbose_name='الكتاب')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_document_attachments', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق أرشيفي',
                'verbose_name_plural': 'المرفقات الأرشيفية',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['uploaded_at'], name='api_archive_uploade_8597fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='archivedocument',
            index=models.Index(fields=['document_number'], name='api_archive_documen_1ae27c_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedocument',
            index=models.Index(fields=['document_date'], name='api_archive_documen_8a6b62_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedocument',
            index=models.Index(fields=['document_kind'], name='api_archive_documen_3811c1_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedocument',
            index=models.Index(fields=['status'], name='api_archive_status_3c19a6_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedocument',
            index=models.Index(fields=['storage_number'], name='api_archive_storage_e5f480_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedocument',
            index=models.Index(fields=['file_number'], name='api_archive_file_nu_123445_idx'),
        ),
        migrations.AddConstraint(
            model_name='archivedocument',
            constraint=models.UniqueConstraint(fields=('document_number', 'document_date'), name='uniq_document_number_document_date'),
        ),
    ]
